global using BlazorComponent;
global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Components.Web;
global using Microsoft.AspNetCore.Http;
global using TMV.Web.Core.Global;
global using TMV.Web.Core.Global.Config;
global using TMV.Web.Core.Global.Nav.Model;
global using TMV.Web.Core;
global using Mapster;
