global using System.Collections.Generic;
global using System;
global using System.Linq;
global using System.ComponentModel.DataAnnotations;
global using System.IO;
global using System.Net.Http;
global using System.Net.Http.Json;
global using System.Reflection;
global using System.Threading.Tasks;